# include:
#   - compose.observability.yaml
services:
  speaches:
    container_name: speaches-cpu
    extends:
      file: compose.yaml
      service: speaches
    # Use locally built image instead of pulling from registry
    # Build with: docker build --platform linux/arm64 -t openai-tts-server:cpu -f Dockerfile.cpu .
    image: openai-tts-server:cpu
    # Don't include build config here to avoid multi-platform issues from compose.yaml
    volumes:
      # Override to use local HuggingFace cache instead of named volume
      - ${HF_HOME:-~/.cache/huggingface}:/home/ubuntu/.cache/huggingface
      # Mount voices directory for StyleTTS2
      - ./voices:/home/ubuntu/speaches/voices:ro
